### ISSUE TITLE
get_product_for_prompt Is not defined

### ISSUE THREAD

**Issue by sisco0** [nicoladisabato/OrderBot#1]
The `get_products_for_initial_prompt` function is used under `openai_functions.py` functions file.
The cited function redirects to _MySql_ procedure `get_product_for_prompt`, which is not defined under `script.sql` file.
A fix should be provided, where `script.sql` be updated to contain `get_product_for_prompt` procedure.

Thank you, @nicoladisabato, for posting this application in [Medium](https://medium.com/@nicoladisabato_19197/ordering-products-through-llm-based-chatbots-using-natural-language-d5e850342e8d).

Evidence:
```
Traceback (most recent call last):
  File "/home/tbd/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 661, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: PROCEDURE restaurant_db.get_product_for_prompt does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tbd/dev/OrderBot/main.py", line 2, in <module>
    import openai_functions
  File "/home/tbd/dev/OrderBot/openai_functions.py", line 25, in <module>
    input_list = db_helper.get_products_for_initial_prompt()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbd/dev/OrderBot/db_helper.py", line 29, in get_products_for_initial_prompt
    cursor.callproc('get_product_for_prompt')
  File "/home/tbd/.local/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 586, in callproc
    result = self._cnx.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/tbd/.local/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 83, in wrapper
    result = method(cnx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbd/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 669, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE restaurant_db.get_product_for_prompt does not exist
```

**Comment by joaquinsanchez97** [comment]
I had the exact same problem

**Comment by 0xcaffeinated** [comment]
Any updates on this?

**Comment by 0xcaffeinated** [comment]
Can someone share the rectified `script.sql` here?
